CREATE TABLE IF NOT EXISTS ar_progress (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id BIGINT UNSIGNED NOT NULL,
  content_id BIGINT UNSIGNED NOT NULL,
  next_position INT DEFAULT 1,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,

  FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pontuacoes (
    user_id BIGINT UNSIGNED NOT NULL,
    activity_id BIGINT UNSIGNED NOT NULL,
    pontuacao BIGINT NOT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    tempo_restante INT NOT NULL DEFAULT 0,

    PRIMARY KEY(user_id, activity_id),
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(activity_id) REFERENCES activities(id) ON DELETE CASCADE
) ENGINE=InnoDB;

ALTER TABLE schools
ADD COLUMN publico TINYINT NOT NULL DEFAULT 0;

ALTER TABLE contents
ADD COLUMN sort_activities TINYINT DEFAULT 0;
ADD COLUMN refeito TINYINT NOT NULL DEFAULT 0,

ALTER TABLE activities 
ADD COLUMN position INT NOT NULL DEFAULT 0,
ADD COLUMN duration INT DEFAULT NULL,
ADD COLUMN score INT DEFAULT NULL;
ADD COLUMN hint VARCHAR(255) DEFAULT NULL;

ALTER TABLE student_answers 
ADD COLUMN tentativas INT NOT NULL DEFAULT 1;

ALTER TABLE content_developer
ADD CONSTRAINT fk_content_developer_content
FOREIGN KEY (content_id) REFERENCES contents(id)
ON DELETE CASCADE;

ALTER TABLE users
ADD COLUMN avatar VARCHAR(400) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS jogos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  content_id BIGINT UNSIGNED NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS regras (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  pontMax INT NOT NULL,
  tempo INT NOT NULL
);

CREATE TABLE IF NOT EXISTS salas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  jogo_id BIGINT UNSIGNED NOT NULL,
  regra_id BIGINT UNSIGNED NOT NULL,
  turma_id BIGINT UNSIGNED NOT NULL,
  nome VARCHAR(255) NOT NULL,
  aberta BOOLEAN NOT NULL DEFAULT 0,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL,

  FOREIGN KEY (jogo_id) REFERENCES jogos(id) ON DELETE CASCADE,
  FOREIGN KEY (regra_id) REFERENCES regras(id) ON DELETE CASCADE,
  FOREIGN KEY (turma_id) REFERENCES turmas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pontuacao_salas(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  aluno_id BIGINT UNSIGNED NOT NULL,
  sala_id BIGINT UNSIGNED NOT NULL,
  pontuacao BIGINT NOT NULL,

  FOREIGN KEY (sala_id) REFERENCES salas(id) ON DELETE CASCADE,
  FOREIGN KEY (aluno_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `random_sorts` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` bigint UNSIGNED NOT NULL,
  `content_id` bigint UNSIGNED NOT NULL,
  `sort` char(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`content_id`) REFERENCES `contents`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

ALTER TABLE salas
ADD COLUMN started_at TIMESTAMP NULL;

CREATE TABLE IF NOT EXISTS `sala_aluno` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `sala_id` BIGINT UNSIGNED NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL,
    `updated_at` TIMESTAMP NULL DEFAULT NULL,
    
    PRIMARY KEY (`id`),
    
    UNIQUE KEY `sala_aluno_sala_id_user_id_unique` (`sala_id`, `user_id`),
    
    CONSTRAINT `sala_aluno_sala_id_foreign` FOREIGN KEY (`sala_id`) REFERENCES `salas` (`id`) ON DELETE CASCADE,
    CONSTRAINT `sala_aluno_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
);